import {instrument_sans} from "@/fonts/instrument_sans";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={instrument_sans.className + " border-4 rounded-lg border-purple-500 min-h-screen"}>{children}</body>
    </html>
  );
}
