import {instrument_sans} from "@/fonts/instrument_sans";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import Link from "next/link";
import {ibm_plex_mono} from "@/fonts/ibm_plex_mono";
import AddYourStartupBottomPanel from "@/components/AddYourStartupBottomPanel";
import { headers } from "next/headers";
import Navbar from "@/components/Navbar";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    const headersList = headers();
    const pathname =  headersList.get("x-pathname")
    console.log(pathname)
    return (
        <ClerkProvider>
            <html lang="en">
            <body
                className={instrument_sans.className + " border-4 rounded-lg border-purple-500 min-h-screen"}>
            <AddYourStartupBottomPanel />

            {children}</body>
            </html>
        </ClerkProvider>
    );
}
